project:
  type: website
    
website:
  open-graph: true
  title: "Data Science PD newsletter"
  description: "A newsletter promoting professional development for data scientists at NHS England."
  site-url: https://harrietrs.github.io/pd_newsletter
  favicon: docs/_assets/favicon.ico
  repo-url: https://github.com/harrietrs/pd_newsletter
  repo-actions: [edit, issue]

  page-footer:
    left: "This page is built [Quarto](https://quarto.org/)."
    right:
    - text: "License"
      href: https://github.com/harrietrs/pd_newsletter/blob/main/LICENCE

  navbar:
    background: light
    title: false
    collapse-below: lg
    left:
      - text: "Newsletter"
        icon: "box-seam"
        href: index.qmd
    right:
      - text: "Archive"
        href: archive.qmd
      - text: "About"
        icon: "info-circle"
        href: about.qmd
      - text: "Help"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/harrietrs/pd_newsletter/issues"
      - icon: github
        href: https://github.com/harrietrs/
        aria-label: GitHub
format:
  html:
    toc: true
    toc-depth: 4
    theme:
      light: [cosmo, _assets/style/theme.scss]
    code-copy: true
    code-overflow: wrap
    css: _assets/style/styles.css
    include-after-body: _assets/style/js.html

execute:
  freeze: auto